services:

  web:
    build: .
    container_name: helpdesk_web

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db


  db:
    image: postgres:16
    container_name: helpdesk_db

    environment:
      POSTGRES_DB: helpdesk_db
      POSTGRES_USER: helpdesk_user
      POSTGRES_PASSWORD: helpdesk_password

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: