# Generated by Django 6.0.7 on 2026-07-14 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('dependencia_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_hijas', to='core.dependencia', verbose_name='dependencia superior')),
                ('jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='jefe de dependencia')),
            ],
            options={
                'verbose_name': 'dependencia',
                'verbose_name_plural': 'dependencias',
                'ordering': ['nombre'],
            },
        ),
    ]
